name: dash
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - plotly
  - plotly=5.6.0
  - jupyterlab>=3
  - ipywidgets>=7.6
  - jupyter-dash
  - numpy=1.21.*
  - pandas=1.3.5
  - pip

  - pip:
      - 
